---
- name: Converge NTP
  hosts: all
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: gwerlas.time
      vars:
        time_backend_name: ntp
        time_servers:
          - 0.fr.pool.ntp.org
          - 1.fr.pool.ntp.org
          - 2.fr.pool.ntp.org
          - 3.fr.pool.ntp.org
