---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: debian10
    box: debian/buster64
    provider_raw_config_args: &raw_config
      - "cpu_mode = 'host-passthrough'"
      - "disk_bus = 'virtio'"
      - "nic_model_type = 'virtio'"
      - "video_type = 'virtio'"
      - "disk_driver :cache => 'writeback'"
      - "storage :file, bus: 'virtio', cache: 'writeback'"
  - name: debian11
    box: debian/bullseye64
    provider_raw_config_args: *raw_config
  - name: el7
    box: centos/7
    provider_raw_config_args: *raw_config
  - name: ubuntu1804
    box: generic/ubuntu1804
    provider_raw_config_args: *raw_config
  - name: ubuntu2004
    box: generic/ubuntu2004
    memory: 2048
    provider_raw_config_args: *raw_config
  - name: ubuntu2204
    box: generic/ubuntu2204
    memory: 2048
    provider_raw_config_args: *raw_config
  - name: ubuntu2210
    box: generic/ubuntu2210
    memory: 2048
    provider_raw_config_args: *raw_config
lint: ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
