---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: archlinux
    box: archlinux/archlinux
    provider_raw_config_args: &raw_config
      - "cpu_mode = 'host-passthrough'"
      - "disk_bus = 'virtio'"
      - "nic_model_type = 'virtio'"
      - "video_type = 'virtio'"
      - "disk_driver :cache => 'writeback'"
      - "storage :file, bus: 'virtio', cache: 'writeback'"
  - name: debian12
    box: debian/testing64
    provider_raw_config_args: *raw_config
  - name: el8
    box: generic/centos8s
    memory: 2048
    provider_raw_config_args: *raw_config
  # Temporarily disabled due to selinux permissions bug
  # - name: el9
  #   box: generic/centos9s
  #   memory: 2048
  #   provider_raw_config_args: *raw_config
  - name: gentoo
    box: generic/gentoo
    cpus: 4
    memory: 8192
    provider_raw_config_args:
      - "cpu_mode = 'host-passthrough'"
      - "nic_model_type = 'virtio'"
      - "video_type = 'virtio'"
      - "disk_driver :cache => 'writeback'"
      - "storage :file, bus: 'virtio', cache: 'writeback'"
lint: ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
