---
- name: Verify role with the server profile (default)
  hosts: all,!gentoo
  gather_facts: false
  tasks:
    - name: Systemd
      ansible.builtin.command:
        cmd: timedatectl
      register: result
      failed_when: |
        (result.rc > 0) or
        ('synchronized: yes' not in result.stdout) or
        ('service: active' not in result.stdout)
      changed_when: false
