---
- name: Verify role with the server profile (default)
  hosts: all
  gather_facts: false
  tasks:
    - name: Systemd
      ansible.builtin.command:
        cmd: timedatectl
      register: result
      failed_when: "result.rc > 0 or 'synchronized: yes' not in result.stdout"
      changed_when: false
